<?php
/**
 * Implements hook_form_alter().
 */
function new_ops_form_alter(&$form, &$form_state, $form_id) {
  $form['title']['#description'] = t('Enter the name of the contract as stated in the Contract.');
  $form['search_block_form']['#attributes']['title'] = t('Search for a contract');
  $form['search_block_form']['#attributes']['placeholder'] = t('enter search terms');
   
  //drupal_set_message($form_id);  // print form ID to messages
  //drupal_set_message(print_r($form, TRUE));  // print array to messages
}

?>